### ISSUE TITLE
Why we can't reconfigure TrustKit?

### ISSUE THREAD

**Issue by novixon** [datatheorem/TrustKit#123]
Hi! Thank you for the great framework!

I want to know why there is no way to update pins (Public Key Hashes, I mean) in TrustKit after we have   initialized it. I think that we should have an ability to update our pins in order to change the outdated one without releasing new version of our App. Am I wrong?

Thanks!

**Comment by nabla-c0d3** [comment]
Hello,
Re-configuring TrustKit while the App is running would not work properly because of how the TLS cache works on iOS: the new configuration would not actually be applied until the TLS cache has been reset by the OS. This is why TrustKit can only be initialized once.

Hence, the right approach here is to change the configuration between restarts of the App, which can already be done for example by storing the configuration in a file in the App's container, and updating with the new configuration as needed. Then, on startup, TrustKit should retrieve this file and use it for initialization.

Does that make sense?

**Comment by novixon** [comment]
@nabla-c0d3 Thank you for your response!

But what if I want to change my pins dynamically? For example, my certificate changed and I don't want to make a new build of my app (with a new configuration). So I will try to download this info from my server (I mean, new pins).

Of course, it can be reconfigured on the next launch time, but it can also be a very long period of time until it happens (if I don't kill my app explicitly). Could you give me an advice about that?

**Comment by novixon** [comment]
Also, @nabla-c0d3, thank you for the explanation about TLS cache!

It's an interesting subject and I tried to read more about it. For example, it is said here (https://developer.apple.com/library/content/qa/qa1727/_index.html) that NSURLSession maintains its own TLS session cache.

So I wonder, if  we can play with it and recreate session to achieve some of the desired behavior? (I mean ability to reconfigure TLS and TrustKit)

**Comment by dlow-yahoo-inc** [comment]
You have a bigger problem with expiring certificates. 
If you don't trust the old pins to your server, how would you trust the new pins being downloaded from it?

Even if you try to update before expiry, eventually they will expire and late updating apps will be toast until they update.
You might consider a forced update message when the pins fail. But you will need to tell the difference from an attack vs. expired pins.

Sent from Yahoo Mail for iPhone


On Monday, July 3, 2017, 10:07 AM, Gleb Novik <notifications@github.com> wrote:


Also, @nabla-c0d3, thank you for the explanation about TLS cache!

It's an interesting subject and I tried to read more about it. For example, it is said here (https://developer.apple.com/library/content/qa/qa1727/_index.html) that NSURLSession maintains its own TLS session cache.

So I wonder, if we can play with it and recreate session to achieve some of the desired behavior? (I mean ability to reconfigure TLS and TrustKit)

**Comment by nabla-c0d3** [comment]
@novixon Although the Apple documentation states that different sessions use a different TLS cache, it's not actually true; I know it because it caused a lot of problems with the TrustKit unit tests. To be honest, this caching layer is very opaque and complex, and is better left untouched.

Overall, allowing pins to be changed dynamically makes it even easier to make a big mistake and brick your App. The right approach here I think is to use an expiration date in your pinning policy and rely on App updates for updating the pins (which should not occur more than once a year). 

If disaster strikes and the certificates must be changed right away on the server, you should have previously set a backup pin in your existing policy specifically for that purpose.

**Comment by novixon** [comment]
@nabla-c0d3 Thank you again for your research and explanation :)

@dlow-yahoo-inc Yeah, I see. I think that this problem can be solved. You can download new pins from a trusted source. For example, you can use a self-signed certificate. So yes, you will not have a chance to update it without new build but you can update pins for other hosts eventually. Doest it make sense?

**Comment by cristian1206** [comment]
> Hi, @nabla-c0d3! Thank you for your response!
> 
> But what if I want to change my pins dynamically? For example, my certificate changed and I don't want to make a new build of my app (with a new configuration). So I will try to download this info from my server (I mean, new pins).
> 
> Of course, it can be reconfigured on the next launch time, but it can also be a very long period of time until it happens (if I don't kill my app explicitly). Could you give me an advice about that?

I am trying to implement this same development so that every time I start the app the pins are loaded from my server and trustkit is reconfigured with the new pins. In my case it is a react-native app for which I built a bridge that does this initialization, as shown in the following image:

![image](https://github.com/datatheorem/TrustKit/assets/53628341/6ea91e05-6782-40df-99eb-ddae61225ffd)

Code module: 
#import "SslPublicKeyPinning.h"

#import "TrustKit/TrustKit.h"

#import <React/RCTHTTPRequestHandler.h>

static NSString *ErrorDomain = @"SslPublicKeyPinningErrorDomain";

static NSString *kIncludeSubdomains = @"includeSubdomains";
static NSString *kPublicKeyHashes = @"publicKeyHashes";


static NSString *PinningErrorEventName = @"pinning-error";
static NSString *kServerHostname = @"serverHostname";

static TrustKit *trustKitInstance = nil;

@implementation SslPublicKeyPinning {
    bool hasListeners;
}
RCT_EXPORT_MODULE()

- (NSArray<NSString *> *) supportedEvents {
    return @[PinningErrorEventName];
}

- (void) startObserving {
    hasListeners = YES;
}

- (void) stopObserving {
    hasListeners = NO;
}

- (void) emitPinningErrorEvent:(NSString *)serverHostname {
    [self sendEventWithName:PinningErrorEventName body:@{ kServerHostname: serverHostname }];
}

- (void) initializeTrustKit:(NSDictionary *)options {
    NSMutableDictionary *pinnedDomains = [NSMutableDictionary dictionary];
    
    NSArray *keys = [options allKeys];
    for (NSString *domain in keys) {
        NSDictionary *domainOptions = [options valueForKey:domain];
        
        [pinnedDomains setObject:@{
            kTSKIncludeSubdomains: @([[domainOptions objectForKey:kIncludeSubdomains] boolValue]),
            kTSKPublicKeyHashes: [domainOptions valueForKey:kPublicKeyHashes],
            kTSKDisableDefaultReportUri: @YES,
        } forKey:domain];
    }
    
    trustKitInstance = [[TrustKit alloc] initWithConfiguration:@{ kTSKPinnedDomains: pinnedDomains }];
    trustKitInstance.pinningValidatorCallback = ^(TSKPinningValidatorResult * _Nonnull result, NSString * _Nonnull notedHostname, TKSDomainPinningPolicy * _Nonnull policy) {
        if (!self->hasListeners || result.evaluationResult != TSKTrustEvaluationFailedNoMatchingPin) {
            return;
        }
        [self emitPinningErrorEvent:result.serverHostname];
    };
}

RCT_REMAP_METHOD(initialize,
                 options:(NSDictionary *)options
                 withResolver:(RCTPromiseResolveBlock)resolve
                 withRejecter:(RCTPromiseRejectBlock)reject)
{
    @try {
        [self initializeTrustKit:options];
        resolve(nil);
    }
    @catch (NSException *exception)
    {
        reject(exception.name, exception.reason,
               [NSError errorWithDomain: ErrorDomain
                                   code: -2
                               userInfo: exception.userInfo]);
    }
}

RCT_REMAP_METHOD(disable,
                 withResolver:(RCTPromiseResolveBlock)resolve
                 withRejecter:(RCTPromiseRejectBlock)reject)
{
    trustKitInstance = nil;
    resolve(nil);
}

// Don't compile this code when we build for the old architecture.
#ifdef RCT_NEW_ARCH_ENABLED
- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
(const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<facebook::react::NativeSslPublicKeyPinningSpecJSI>(params);
}
#endif

@end

@implementation RCTHTTPRequestHandler (SslPublicKeyPinning)

- (void)URLSession:(NSURLSession *)session
              task:(NSURLSessionTask *)task
didReceiveChallenge:(NSURLAuthenticationChallenge *)challenge
 completionHandler:(void (^)(NSURLSessionAuthChallengeDisposition disposition, NSURLCredential *credential))completionHandler
{
    // Pass the authentication challenge to the validator; if the validation fails, the connection will be blocked
    if (trustKitInstance == nil
        || ![[trustKitInstance pinningValidator] handleChallenge:challenge completionHandler:completionHandler])
    {
        // TrustKit did not handle this challenge: perhaps it was not for server trust
        // or the domain was not pinned. Fall back to the default behavior
        completionHandler(NSURLSessionAuthChallengePerformDefaultHandling, nil);
    }
}

@end

But given other needs that I have, I don't know if you have found a solution for reconfiguring Trukit at runtime?
