### ISSUE TITLE
swizzle NSStream?

### ISSUE THREAD

**Issue by evollu** [datatheorem/TrustKit#145]
Looks like NSStream is not swizzled by TrustKit and react-native's socket implementation is using that.
Is that possible to do?

This link might be helpful?
https://stackoverflow.com/questions/28413923/ssl-handshake-with-my-certificate-by-nsstream

**Comment by nabla-c0d3** [comment]
Hello,
Swizzling tends to make the code a lot more complex, and also a lot harder to maintain. While we still support swizzling for NSURLConnection and NSURLSession, we advise developers to disable it and instead implement the proper code to call into TrustKit, in order to avoid the complexity of the swizzling implementation. 
Because of this we will not add swizzling for more APIs (such as NSStream).
