### ISSUE TITLE
Swizzling fails on shared NSURLSession with completion handler

### ISSUE THREAD

**Issue by pyrosphere** [datatheorem/TrustKit#157]
In a very simple Swift 4 app I'm using the shared URLSession with completion handler:

```
URLSession.shared.dataTask(with: url) { (data, response, error) in
  // handler data/response/error
}.resume()
```

Swizzling fails for this URLSession because the delegate is nil:

https://github.com/datatheorem/TrustKit/blob/51c340fab3cd7ba160a8cf744056c097ab3f96c8/TrustKit/Swizzling/TSKNSURLSessionDelegateProxy.m#L42-L47

I'm not sure why a non-nil delegate is a requirement for swizzling. It works fine after commenting this condition and the assert:

https://github.com/datatheorem/TrustKit/blob/51c340fab3cd7ba160a8cf744056c097ab3f96c8/TrustKit/Swizzling/TSKNSURLSessionDelegateProxy.m#L72

**Comment by nabla-c0d3** [comment]
Hello,

If I remember well, if the delegate is nil, a default system delegate is used, but TrustKit has no way to call it (because it has no references to it). We could just force NSURLSession to use our TrustKit delegate but I am not sure what the implications are there as it changes the app's flow.

Also, swizzling is there only for very simple apps but is not the preferred method for integrating TrustKit (due to the complexity of swizzling), and I'd rather not touch this part of the code. 

It is better to directly call into TrustKit.
