### ISSUE TITLE
Pinning for .corp Domains

### ISSUE THREAD

**Issue by paulroper** [datatheorem/TrustKit#173]
Hey, thanks for your hard work on the framework!

We're looking to pin a cert for a .corp domain but we get a "TrustKit was initialized with an invalid domain" error when the app initialises. Could .corp be added to the TLD list?

**Comment by nabla-c0d3** [comment]
Hey, thanks! 
It looks like .corp will never be a public TLD (https://www.theregister.co.uk/2018/02/12/icann_corp_home_mail_gtlds/), so you will not be able to register a .corp domain or buy an SSL certificate for it. 
Using a private CA is a use case that is not supported by TrustKit (nor iOS since iOS 11 requires manually importing the private CA cert on every device that uses your app).
