### ISSUE TITLE
Pinning With Alamofire

### ISSUE THREAD

**Issue by hamedaakhlaghi** [datatheorem/TrustKit#196]
Is there any way to implement pining with TrustKit and Alamofire?

**Comment by igorkulman** [comment]
I did it just by using the swizzling options, works for Alamofire as it is based in URLSession.

**Comment by hamedaakhlaghi** [comment]
It resolved with https://stackoverflow.com/a/54762838/5391914

**Comment by annathomasQB** [comment]
Hi ,
I'm also trying to do the same. I checked the links above, but the issue with our code is we're not using SessionManager or URLSession, but Session

So making a request is like this : 

```
    let session = Session(eventMonitors: [ Logger() ])
                let request = session.request(requestURL,
                                              method: requestModel.getHTTPMethod(),
                                              parameters: parameters,
                                              encoding: requestModel.getEncodingMethod(),
                                              headers: headers,
                                              interceptor: nil)
                
                handleRequest(request: request,
                              of: response,
                              successBlock: successBlock,
                              failureBlock: failureBlock)


```
So I'm not able to identify where exactly I should be putting in the PinningValidator Code.

I was able to add the pinningPolicy code in didFinishLaunchingWithOptions, but am pretty stuck on where to add the PinningValidator code. 

What I've tried: 
I tried setting the URLSessionDelegate as our BaseAPI, but since I'm not having an instance of URLSession, but that of session only, this isn't working either. 
This is how the session is set in our code :

**Comment by hamedaakhlaghi** [comment]
@annathomasQB use [this link](https://medium.com/flawless-app-stories/ssl-pinning-254fa8ca2109), Please see what is `Session(...)` in your code, I think it is `URLSession`

**Comment by annathomasQB** [comment]
@hamedaakhlaghi 
Thanks for the link. I'll check it out.
`Session()` is an open class Session with no type defined from file Session.swift in Alamofire. It has a public variable session which is of type URLSession
<img width="813" alt="Screenshot 2020-09-28 at 10 59 19 AM" src="https://user-images.githubusercontent.com/2297073/94393905-b2f4f280-0179-11eb-91e4-88223c785941.png">

**Comment by hamedaakhlaghi** [comment]
`Session` is for `Alamofire5`, I do this task with `Alamofire 4`, I think they changed `SessionManager` to `Session`. the solution for `Alamofire 4` is [here](https://stackoverflow.com/a/54762838/5391914)
