### ISSUE TITLE
Pin Configuration from get_pin_from_* scripts only provide single hash 

### ISSUE THREAD

**Issue by Ashton-W** [datatheorem/TrustKit#29]
```
$ sh get_pin_from_server.sh www.datatheorem.com
----------------------------
Top Intermediate Certificate
----------------------------
subject= /C=US/O=thawte, Inc./OU=Certification Services Division/OU=(c) 2006 thawte, Inc. - For authorized use only/CN=thawte Primary Root CA
issuer= /C=ZA/ST=Western Cape/L=Cape Town/O=Thawte Consulting cc/OU=Certification Services Division/CN=Thawte Premium Server CA/emailAddress=premium-server@thawte.com
SHA1 Fingerprint=1F:A4:90:D1:D4:95:79:42:CD:23:54:5F:6E:82:3D:00:00:79:6E:A2
--------------------------
TrustKit Pin Configuration
--------------------------
kTSKPublicKeyHashes: @[@"HXXQgxueCIU5TTLHob/bPbwcKOKw6DkfsTWYHbxbqTY="]
kTSKPublicKeyAlgorithms: @[kTSKAlgorithmRsa2048]
```

The Pin Configuration returned won't work as TrustKit requires at least 2 hashes:

`*** Terminating app due to uncaught exception 'TrustKit configuration invalid', reason: 'TrustKit was initialized with less than two pins (ie. no backup pins) for domain www.datatheorem.com'`

How do we go about getting a backup hash, and shouldn't the scripts provide it?

**Comment by nabla-c0d3** [comment]
The backup pin is not something you can get from the server. It is from a "backup" CSR you would generate and keep, in case you need to swap the server's initial certificate (because it expired/got compromised/etc.). See this post for more information on how to generate one https://noncombatant.org/2015/05/01/about-http-public-key-pinning/.
