### ISSUE TITLE
TrustKit Crashing

### ISSUE THREAD

**Issue by jkanter** [datatheorem/TrustKit#32]
We are getting NUMEROUS instances of TrustKit crashing and it seems to be when it sends reports:

http://crashes.to/s/9168aa90a10

I'm ammending my Issue because I see that there is a **kTSKDisableDefaultReportUri** which I should have set to NO.  So apparently any failed request is being sent to your server also. This hits my point below from the original Issue

Why would you crash the app if it fails to save the Report?  Wouldn't it make sense to just not send the report if it can't save it?  I'm not sure why our real world users are unable to save the report to their device but We're getting like 30 crashes from 20 different users as a result...

**Comment by nabla-c0d3** [comment]
Hi,
Yes, this needs to be changed. 
It was done this way because it didn't seem like there would be a scenario where the report can't be saved; turns out apparently there is one. Could it be that the disk is full ? Reports are very small so this would be surprising. Also, there are a few Apps with very large user bases that have already deployed TrustKit and didn't run into that issue, so any additional information you can get would be useful.
Regardless, I will release 1.2.1 next week with a small fix.

**Comment by jkanter** [comment]
I certainly agree with you that it doesn't really make much sense why this is happening...but it is.  Unfortunately that's always the way coding works.  The last thing you'd expect is the one thing that happens, ha.

Thanks!

**Comment by nabla-c0d3** [comment]
The exception is now only raised in Debug builds, just to make sure we can detect if something is really wrong with the background uploader (ie. writing the file fails constantly).

**Comment by nabla-c0d3** [comment]
FYI we're also seeing your pinning reports in our dashboard - feel free to contact me if you'd like to have a look.
