### ISSUE TITLE
RSA 1024

### ISSUE THREAD

**Issue by ricardolpd** [datatheorem/TrustKit#38]
Hi, 
I have a development certificate that uses RSA1024, which is not currently supported by trustkit, however i need to add this to our current application.

Is it possible for you guys to tell me how do you guys get the ASN1 headers from the certificates, so i can add this to the script and the trustkit, if it brings value to you guys i could potentially fork and merge back the changes. Let me know regards

Regards

**Comment by nabla-c0d3** [comment]
Hi,
TrustKit does not support RSA 1024 by design, as it is unsafe. Any way you could re-generate your test certificate? To get the ASN1 SPKI headers I had to manually look at a certificate with the algorithm I was looking for and extract the byte sequence using a hex editor and a certificate parser (such as https://redkestrel.co.uk/products/decoder/).

**Comment by ricardolpd** [comment]
Hi, 

This is a development certificate, and unfortunately the department that creates them are not helpful at all.
I also tried to do that, but i struggle to find out where does the ASN1 header finishes in the public key, how do you know how long it is.

**Comment by nabla-c0d3** [comment]
I used this tool to look at the ASN1 sequences: http://lapo.it/asn1js/

**Comment by ricardolpd** [comment]
thanks that sorted it:).
