### ISSUE TITLE
Pinning error looks like cancelled operation

### ISSUE THREAD

**Issue by ppaulojr** [datatheorem/TrustKit#39]
This is the error when pinning fails.
```
(lldb) po error
Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLKey=https://evolve.cipherhealth.com/api/orchid/authentication, NSErrorFailingURLStringKey=https://evolve.cipherhealth.com/api/orchid/authentication, NSLocalizedDescription=cancelled}
```

So there's no specific way to report back to the user that there's a security failure.

**Comment by nabla-c0d3** [comment]
Hello,

This is due to iOS' SSL caching layer, which causes the NSURLConnection/NSURLSession delegate handler to not be called when receiving the server's certificate, and instead cancels the connection early, thereby returning this vague error; this happens when the server's SSL certificate had previously been rejected (ie. the delegate handler called `cancelAuthenticationChallenge:`). 

I don't think there is anything we can do at our level as it is an iOS issue. There are more details in this thread:

https://github.com/AFNetworking/AFNetworking/pull/3169

**Comment by ppaulojr** [comment]
@idelgado FYI this was the answer.

**Comment by sevenbanks** [comment]
Any better way to translate this -999 error into one of the SSL pinning errors defined by TrustKit?
