### ISSUE TITLE
s3.amazonaws.com erroneously recognised as a domain suffix

### ISSUE THREAD

**Issue by sja26** [datatheorem/TrustKit#42]
I want to enable certificate pinning against multiple Amazon S3 buckets, I've configured TrustKit in the AppDelegate, sample Xcode project attached: [TrustKitWithAmazonS3.zip](https://github.com/datatheorem/TrustKit/files/250119/TrustKitWithAmazonS3.zip)

On launching the app an exception is raised: `Terminating app due to uncaught exception 'TrustKit configuration invalid', reason: 'TrustKit was initialized with includeSubdomains for a domain suffix s3.amazonaws.com'`

Why is it considered a domain suffix (if it's not a bug), and what is the correct way to configure certificate pinning for subdomains of `s3.amazonaws.com`?

What I've tried so far:
- setting the pinned domain to `s3.amazonaws.com`: raises exception
- setting the pinned domain to `*.s3.amazonaws.com`: doesn't raise exception but certificate pinning fails on subdomains
- setting the public key hash from the server certificate with `CN=s3.amazonaws.com`: no effect
- setting the public key hash from the server certificate with `CN=*.s3.amazonaws.com`: no effect

Certificates obtained using `openssl s_client -showcerts -connect s3.amazonaws.com:443`

Output from the `get_pin_from_certificate.py` script to obtain the Public Key Hashes:

    $ ./get_pin_from_certificate.py s3-amazonaws.pem

    CERTIFICATE INFO
    ----------------
    subject= /C=US/ST=Washington/L=Seattle/O=Amazon.com Inc./CN=s3.amazonaws.com
    issuer= /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Baltimore CA-2 G2
    SHA1 Fingerprint=65:B0:62:58:C9:E6:5C:07:A5:6A:39:DB:88:7A:EA:0F:3F:14:42:75

    TRUSTKIT CONFIGURATION
    ----------------------
    kTSKPublicKeyHashes: @[@"tfR4WIM3cjezQdf3yh/px0abP/kN6KbYruem43CT1t8="] // You will also need to configure a backup pin
    kTSKPublicKeyAlgorithms: @[@"TSKAlgorithmRsa2048"]
    
    $ ./get_pin_from_certificate.py star-s3-amazonaws.pem

    CERTIFICATE INFO
    ----------------
    subject= /C=US/ST=Washington/L=Seattle/O=Amazon.com Inc./CN=*.s3.amazonaws.com
    issuer= /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Baltimore CA-2 G2
    SHA1 Fingerprint=3B:E4:04:74:1F:F3:01:E3:03:0D:B7:7F:C7:79:60:84:16:D6:56:B9

    TRUSTKIT CONFIGURATION
    ----------------------
    kTSKPublicKeyHashes: @[@"tzsid6cLOVtz0NnqTUDQU/CmN/bSC5vUQRUj6p7JBF0="] // You will also need to configure a backup pin
    kTSKPublicKeyAlgorithms: @[@"TSKAlgorithmRsa2048"]

    $ ./get_pin_from_certificate.py s3-amazonaws_intermediate_ca.pem 

    CERTIFICATE INFO
    ----------------
    subject= /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Baltimore CA-2 G2
    issuer= /C=IE/O=Baltimore/OU=CyberTrust/CN=Baltimore CyberTrust Root
    SHA1 Fingerprint=A9:D5:30:02:E9:7E:00:E0:43:24:4F:3D:17:0D:6F:4C:41:41:04:FD

    TRUSTKIT CONFIGURATION
    ----------------------
    kTSKPublicKeyHashes: @[@"56higu/MFWb/c2b0avLE5oN2ECS2C43RvzSUgx/2xIE="] // You will also need to configure a backup pin
    kTSKPublicKeyAlgorithms: @[@"TSKAlgorithmRsa2048"]

**Comment by nabla-c0d3** [comment]
Hello,

First of all you should not pin an Amazon domain, unless you work at Amazon. Pinning a domain you do not own means that the certificate/key could change at any time and there is no way for you to manage that in your App, meaning your App will break. You should only pin the domains you control.

As for s3.amazonaws.com, we use Google's library in order to determine whether a string is a domain suffix ( https://github.com/pagespeed/domain-registry-provider ), which uses the public TLD list ( https://publicsuffix.org/list/effective_tld_names.dat ). It is not a bug and there's a discussion about it here: https://github.com/pagespeed/domain-registry-provider . 

If you go to the publicsuffix.org page, it also states that "[a domain on the TLD list] represents the part of a domain name which is not under the control of the individual registrant.", which is the case here; TrustKit preventing you from pinning this domain is the expected behavior.

Hope this helps!
